#!/usr/bin/env bash
#### the /usr/bin/env bash this tells the system to use env to locate the bash interpreter and use bash to execute the script

for ((i=1; i<=10; i++)); do
#the text entered below will repeat itself 10 time
	echo "Best School $i"
done
