#!/usr/bin/env bash
####

i=1

while [ $i -lt 100 ]; do

	if [ $(($i%3)) ]; then
	echo "FizzBuzz"
	elif [ $(($i%3)) ]; then
	echo "Fizz"
	elif [ $(($i%5)) ]; then
	echo "Buzz"
	else
	echo $i
	fi
	((i++))
	done
