#!/usr/bin/env bash
######
i=1

while true; do
	echo "Best School"
    if [ $i -eq 4 ]; then
	echo "bad luck"

    elif [ $i -eq 8 ]; then
	echo "good luck"

    elif [ $i -eq 10 ]; then
	break

    else
	echo "Finished"
    fi
((i++)) 
done
