#!/usr/bin/env bash
##########
i=1
while true; do
    echo "Best School"
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else [ $i -eq 10 ]; then
        echo "Best School"
        break
    fi
    ((i++))
done


