#!/usr/bin/env bash
############
i=1

while [ $i -le 20 ]; do
	case $i in

	   4)
		echo " $i and then bad luck from China\n"

		;;
	   9)

		echo "$i and then bad luck from Japan\n"

		;;

	   17) 

		echo "$i and then bad luck from Italy\n"

		;;

	  *)

		echo $i

		;;

	esac
	((i++))
done
