#!/usr/bin/env bash
########
hours=0

while [ $hours -le 12 ]; do
    echo "Hour: $hours" 
    minutes=0 
    while [ $minutes -le 59 ]; do
        printf "%02d\n" $minutes  
        ((minutes++)) 
    done
    ((hours++)) 
done

